# Generated by Django 5.2.6 on 2025-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
