# Generated by Django 5.2.6 on 2025-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
