# Generated by Django 5.2.6 on 2025-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=8, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
