# Generated by Django 5.2.6 on 2025-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockMang', '0003_alter_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
